### ISSUE TITLE
Error in Query Explain Plugin: Missing field host

### ISSUE THREAD

**Issue by rahul286** [box/Anemometer#83]
I am getting this a single-query page

Any reason?

In my case, host is always localhost.

**Comment by mackinra** [comment]
I'm using that filter exactly as you have it above, but I'm still getting that error ("Error in Query Explain Plugin: Missing field host").

**Comment by hayden-t** [comment]
@mackinra  same here

**Comment by sabikam** [comment]
Hey guys! This issue "Error in Query Explain Plugin: Missing field host" is making using anemometer really painful

**Comment by titpetric** [comment]
In my case the problem is that the hostname was shorter than 5 characters. This limitation can be changed in your config.inc.php. Find this line:

~~~
if (!array_key_exists('hostname_max',$sample) or strlen($sample['hostname_max']) < 5)
~~~

and change the 5 to a 2 (allowing "db", but not allowing "a"). The restriction is slightly silly and obviously not informative of what the actual error is.
A bit lower in the same function, be sure to set the correct $conn['user'] and $conn['password'] values.
